### ISSUE TITLE
[BUG] T0 and T1 temperatures are not displayed independently

### ISSUE THREAD

**Issue by Drzet** [luc-github/ESP3D#607]
**Describe the bug**
While printing with only 1 extruder ESP3D displays the same temperature for both working and idle extruder  

**Expected behavior**
Correct temperature for every tool

**Screenshots**
![temp](https://user-images.githubusercontent.com/5352189/113422272-4a0a6380-93c4-11eb-9bbd-9cf30127dab6.jpg)

**ESP3D Firmware:**
- Version:2.1.1b8
- Web UI Version: 2.1b57

**Target Firmware:**
 - Name: Marlin
 - Version 2.0.x.bugfix

**Board used (please complete the following information):**
SKR v1.4

**Comment by luc-github** [comment]
The latest webUI is 2.1b69  you are using  2.1b57 
Can you confirm issue is still present in latest version ?

**Comment by Drzet** [comment]
I've uploaded the latest index.html.gz, now it shows webUI version 2.1.b60
Issue still present

**Comment by luc-github** [comment]
latest webUI is 2.1b69  in git not 2.1.b60 and I think issue was solved in 2.1b61 - please use latest git

**Comment by Drzet** [comment]
They had b60 within latest release .zip
Got b69, issue still present
![Untitled](https://user-images.githubusercontent.com/5352189/113424923-d9b21100-93c8-11eb-88fd-0b9560586951.png)

**Comment by luc-github** [comment]
ok I will have a look

**Comment by Drzet** [comment]
Seems like it's reporting the "T", not separately T0..Tx

**Comment by luc-github** [comment]
Yes indeed - I am on it, I think I fixed this in 3.0 - I will fix this one too

**Comment by luc-github** [comment]
[index.html.gz](https://github.com/luc-github/ESP3D/files/6250084/index.html.gz)
Please let me know if this one fix the issue - New version should be 70

**Comment by Drzet** [comment]
![fix](https://user-images.githubusercontent.com/5352189/113427812-9d34e400-93cd-11eb-9c12-af4c4a9afb4c.jpg)

**Comment by luc-github** [comment]
ok great I push the update on github - thank you for reporting issue and feedback

**Comment by luc-github** [comment]
WebUI updated - I move issue to webUI
